services:
  db:
    image: ${DATABASE_TYPE}:latest
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    expose:
      - 5432
    networks:
      - db_network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    expose:
      - 8080
    networks:
      - nginx_network
      - db_network

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_network
      - nginx_network
    environment:
      DJANGO_DATABASE: ${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    expose:
      - 8000
    volumes:
      - ./backend/team37_api:/app

  react:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: react

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
      react:
        condition: service_completed_successfully
    volumes:
      - ./frontend/dist:/var/www/app/dist
      - ./backend/team37_api/static:/var/www/api/static
      - ./backend/team37_api/media:/var/www/api/media
      - ./nginx/log:/var/log/nginx
    networks:
      - nginx_network
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 8080:8080

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
